version: "3.9"
services:
  api:
    container_name: api
    image: flamingo-frameworks/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    networks:
      - default
  chroma:
    container_name: chroma
    image: chromadb/chroma
    ports:
      - 3002:8000
    networks:
      - default
networks:
  default:
    driver: bridge
