version: "3.9"
services:
  api:
    container_name: api
    image: flamingo-frameworks/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3011:3000
    networks:
      - default
  chroma:
    container_name: chroma
    image: chromadb/chroma
    ports:
      - 8000:8000
    networks:
      - default
    # environment:
      # CHROMA_API_IMPL: rest
      # CHROMA_SERVER_HOST: localhost
      # CHROMA_SERVER_HTTP_PORT: 8000
networks:
  default:
    driver: bridge
